server:
  port: 9000
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: micro-users
          uri: lb://users
          predicates:
            - Path=/api/users/**
        - id: micro-pizzas-read
          uri: lb://pizzas-read
          predicates:
            - Path=/pizzas/read/**
        - id: micro-write-pizzas
          uri: lb://write-pizzas
          predicates:
            - Path=/pizzas/write/**

