version: '3.8'

networks:
  dmh-network:
    driver: bridge

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: pizzas_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - dmh-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres-data:

#  rabbitmq:
#    image: rabbitmq:3.7.6-management
#    container_name: rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    environment:
#      - "TZ=@timezone@"
#    healthcheck:
#      test: [ "CMD", "rabbitmqctl", "status" ]
#      interval: 10s
#      timeout: 5s
#      retries: 10
#
#  zipkin:
#    image: openzipkin/zipkin:2.23.0
#    container_name: zipkin
#    depends_on:
#      rabbitmq:
#        condition: service_healthy
#    ports:
#      - "9411:9411"
#    environment:
#      - "TZ=@timezone@"
#      - "RABBIT_URI=amqp://guest:guest@rabbitmq:5672"

