server:
  port: 8081

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  config:
    activate:
      on-profile: default
  application:
    name: pizzas-read
    zipkin: http://zipkin:9411
  datasource:
    url: jdbc:postgresql://localhost:5432/pizzas_db   # Conexión a la base de datos PostgreSQL
    username: user                                   # Nombre de usuario para PostgreSQL
    password: password                               # Contraseña para PostgreSQL
    driver-class-name: org.postgresql.Driver        # Controlador JDBC de PostgreSQL
  jpa:
    hibernate:
      ddl-auto: update                               # Hibernate actualiza la base de datos según las entidades
    show-sql: true                                   # Mostrar las consultas SQL en los logs
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Dialecto para PostgreSQL
  jackson:
    serialization:
      indent_output: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher