global:
  scrape_interval: 15s  # Intervalo de recolección de métricas

scrape_configs:
  - job_name: 'local-microservices'
    static_configs:
      - targets:
          - 'host.docker.internal:8083'  # user-service
          - 'host.docker.internal:8081'  # pizza-read-service
          - 'host.docker.internal:8082'  # pizza-write-service
        labels:
          group: 'microservices'