global:
  scrape_interval: 15s

scrape_configs:

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]


  - job_name: "users"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["users:8083"]

  - job_name: "pizza-read"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ "pizzas-read:8081" ]

  - job_name: "pizzas-write"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ "pizzas-write:8082" ]