global:
  scrape_interval: 15s

scrape_configs:

  - job_name: "node_exporter"
    static_configs:
      - targets: [ "node-exporter:9100" ]

  - job_name: "pizzas-read"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["localhost:8081"]

  - job_name: 'users'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["localhost:8083"]
