server:
  port: 8081

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  config:
    activate:
      on-profile: default
  application:
    name: pizzas-read
    zipkin: http://zipkin:9411
  datasource:
    url: jdbc:postgresql://localhost:5432/pizzas_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      indent_output: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher