server:
  port: 8081

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: pizzas-read
  datasource:
    url: jdbc:postgresql://localhost:5432/pizzas_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

