server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
spring:
  config:
    activate:
      on-profile: default

  application:
    name: users

  zipkin:
    sender:
      type: rabbit

  sleuth:
    sampler:
      probability: 1.0

  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:usersdb
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  management:
    endpoints:
      web:
        exposure:
          include: health, info, prometheus, metrics

resilience4j.circuitbreaker:
  instances:
    pizza-read:
      registerHealthIndicator: true
      failureRateThreshold: 50
      slidingWindowSize: 10
      waitDurationInOpenState: 30000ms
      permittedNumberOfCallsInHalfOpenState: 3
      minimumNumberOfCalls: 5

logging:
  level:
    root: INFO
    com.tu.paquete: DEBUG