server:
  port: 8083

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  config:
    activate:
      on-profile: default
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:usersdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#
#resilience4j:
#  circuitbreaker:
#    configs:
#      shared:
#        sliding-window-type: count_based #Basado en contador
#        sliding-window-size: 5 #Número de llamadas fallidas permitidas
#        slow-call-rate-threshold: 50 #Porcentaje que vamos a permitir de llamadas fallidas o lentas
#        permitted-number-of-calls-in-half-open-state: 1 #Número de llamadas permitidas en el estado medio abierto
#        max-wait-duration-in-half-open-state: 10s #Tiempo de duración máximo del estado medio abierto
#        wait-duration-in-open-state: 10s #Tiempo duración estado abierto
#        writable-stack-trace-enabled: true #Logs por consola
#        automatic-transition-from-open-to-half-open-enabled: true
#    instances:
#      prendas:
#        base-config: shared