server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
spring:
  application:
    name: write-pizzas
  zipkin:
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0
  datasource:
    url: jdbc:postgresql://postgres:5432/pizzas_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  management:
    endpoints:
      web:
        exposure:
          include: health, info, prometheus, metrics
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher