spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: userService
          uri: lb://users
          predicates:
            - Path=/api/users/**
        - id: pizzas-read
          uri: lb://pizzas-read
          predicates:
            - Path=/pizzas/read/**
        - id: pizzas-write
          uri: lb://pizzas-write
          predicates:
            - Path=/pizzas/write/**

info:
  app:
    name: Gateway
    description: API gateway
    version: 1.0.0

eureka:
  instance:
    hostname: localhost
    statusPageUrlPath: http://localhost:9000/actuator/info
    healthCheckUrlPath: http://localhost:9000/actuator/info
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


server:
  port: 9000