server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      enabled: true
      server:
        native:
          searchLocations: classpath:/configuracion
  profiles:
    active: native

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/