server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: config-server
  cloud:
    config:
      enabled: true
      server:
        native:
          searchLocations: classpath:/configuracion
  profiles:
    active: native